'use client'
import { useEffect, useState } from 'react'
import { CheckCircle2, CircleAlert, Clock3, RefreshCw } from 'lucide-react'
import ConfirmationCard from '@/components/ConfirmationCard'

type Order={id:string;symbol:string;side:string;order_type:string;quantity:number;price?:number|null;trigger_price?:number|null;quoted_price?:number|null;risk_score?:number|null;risk_check_passed?:boolean;risk_reason?:string;status:string;created_at?:string}
const label=(status:string)=>({DRAFT:'Pending approval',APPROVED:'Approved · demo',FILLED:'Executed · demo',PARTIAL:'Part-filled · demo',REJECTED:'Rejected',FAILED:'Failed',CANCELLED:'Cancelled',SUBMITTED:'Submitted · demo',EXPIRED:'Expired'} as Record<string,string>)[status.toUpperCase()]||status
const badge=(status:string)=>['DRAFT','APPROVED','SUBMITTED'].includes(status.toUpperCase())?'status-badge status-pending':['FILLED','PARTIAL'].includes(status.toUpperCase())?'status-badge status-positive':['REJECTED','CANCELLED'].includes(status.toUpperCase())?'status-badge status-negative':'status-badge status-failed'
export default function OrdersApprovals(){const [orders,setOrders]=useState<Order[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selected,setSelected]=useState<Order|null>(null)
 const refresh=async()=>{try{const r=await fetch('http://localhost:8000/orders/');if(!r.ok)throw new Error('Order service is unavailable.');const d=await r.json();setOrders(d.orders||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load order history.')}finally{setLoading(false)}}
 useEffect(()=>{refresh();const t=setInterval(refresh,10000);return()=>clearInterval(t)},[])
 const pending=orders.filter(o=>o.status.toUpperCase()==='DRAFT').length
 return <div className="data-view"><div className="data-view-header"><div><div className="page-kicker">ORDER REVIEW</div><h2>Orders &amp; approvals</h2><p>Review draft details and the simulated broker status for each recorded order.</p></div><button className="quiet-button" onClick={refresh}><RefreshCw size={14}/> Refresh</button></div>
 <div className="order-summary-strip"><span><Clock3 size={15}/> <b>{pending}</b> pending approval</span><span><CheckCircle2 size={15}/> <b>{orders.filter(o=>['FILLED','PARTIAL'].includes(o.status.toUpperCase())).length}</b> executed in demo</span><span className="demo-pill">MOCK BROKER</span></div>
 {error&&<div className="inline-error"><CircleAlert size={15}/>{error}</div>}
 <div className="orders-layout"><div className="data-table-card orders-list"><div className="table-head order-head"><span>ORDER</span><span>QUANTITY</span><span>STATUS</span></div>{loading?<div className="table-state">Loading orders…</div>:orders.length?orders.map(order=><button key={order.id} className={`table-row order-row ${selected?.id===order.id?'row-selected':''}`} onClick={()=>setSelected(order)}><span className="symbol-cell"><b>{order.side} {order.symbol?.replace('.NS','')}</b><small>{order.order_type} · {order.created_at?new Date(order.created_at).toLocaleString():''}</small></span><span>{order.quantity} shares</span><span className={badge(order.status)}>{label(order.status)}</span></button>):<div className="table-state">No orders yet. Approved drafts and demo history will appear here.</div>}</div>
 <aside className="order-detail-pane"><span className="panel-eyebrow">SELECTED ORDER</span>{selected?<><h3>{selected.side} {selected.symbol?.replace('.NS','')}</h3><span className={badge(selected.status)}>{label(selected.status)}</span><div className="order-facts"><div><span>Quantity</span><b>{selected.quantity} shares</b></div><div><span>Order type</span><b>{selected.order_type}</b></div><div><span>Quote at review</span><b>{selected.quoted_price?`₹${Number(selected.quoted_price).toLocaleString('en-IN',{maximumFractionDigits:2})}`:'Not available'}</b></div>{selected.trigger_price&&<div><span>Trigger price</span><b>₹{Number(selected.trigger_price).toLocaleString('en-IN')}</b></div>}<div><span>Risk check</span><b className={selected.risk_check_passed?'positive-text':'muted-text'}>{selected.risk_check_passed?'Passed':selected.risk_reason||'Pending'}</b></div></div>
 {selected.status.toUpperCase()==='DRAFT'?<ConfirmationCard key={selected.id} draft={{order_id:selected.id,symbol:selected.symbol,side:selected.side as 'BUY'|'SELL',order_type:selected.order_type,quantity:selected.quantity,price:selected.price??undefined,trigger_price:selected.trigger_price??undefined,quoted_price:selected.quoted_price??undefined,risk_score:selected.risk_score??undefined,risk_check_passed:selected.risk_check_passed,risk_reason:selected.risk_reason}} onApproved={()=>refresh()} onRejected={()=>refresh()}/>:<div className="inline-notice">{['FILLED','PARTIAL'].includes(selected.status.toUpperCase())?'This status comes from the simulated mock broker. It does not represent a real trade.':'Only unapproved drafts can be acted on. This order status is read-only.'}</div>}</>:<div className="table-state">Choose an order to review its details.</div>}</aside></div>
 </div>
}
