'use client'
import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, BriefcaseBusiness, WalletCards } from 'lucide-react'

type Position={symbol:string;quantity:number;avg_price:number;ltp:number;pnl:number;pnl_pct:number;current_value:number}
export default function PortfolioInsights(){
 const [account,setAccount]=useState<any>(null);const [positions,setPositions]=useState<Position[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 const refresh=async()=>{try{const [a,p]=await Promise.all([fetch('http://localhost:8001/account'),fetch('http://localhost:8001/positions')]);if(!a.ok||!p.ok)throw new Error('Portfolio service is unavailable.');const [ad,pd]=await Promise.all([a.json(),p.json()]);setAccount(ad);setPositions(pd.positions||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load portfolio.')}finally{setLoading(false)}}
 useEffect(()=>{refresh();const t=setInterval(refresh,10000);return()=>clearInterval(t)},[])
 const pnl=positions.reduce((s,p)=>s+Number(p.pnl||0),0)
 return <div className="data-view"><div className="data-view-header"><div><div className="page-kicker">ACCOUNT SNAPSHOT</div><h2>Portfolio insights</h2><p>Holdings and balances supplied by the local mock broker.</p></div><span className="demo-pill">DEMO PORTFOLIO</span></div>
 {error&&<div className="inline-error">{error}</div>}{loading?<div className="table-state">Loading portfolio…</div>:<><div className="portfolio-metrics"><article><span><WalletCards size={15}/> Portfolio value</span><strong>₹{Number(account?.total_value||0).toLocaleString('en-IN',{maximumFractionDigits:0})}</strong><small>Cash and marked positions · demo data</small></article><article><span><BriefcaseBusiness size={15}/> Available funds</span><strong>₹{Number(account?.funds_available||0).toLocaleString('en-IN',{maximumFractionDigits:0})}</strong><small>Mock account balance</small></article><article><span>{pnl>=0?<ArrowUpRight size={15}/>:<ArrowDownRight size={15}/>} Unrealized P&amp;L</span><strong className={pnl>=0?'positive-text':'negative-text'}>{pnl>=0?'+':''}₹{pnl.toLocaleString('en-IN',{maximumFractionDigits:0})}</strong><small>Calculated from the demo position snapshot</small></article></div>
 <div className="data-table-card"><div className="positions-title"><h3>Open positions</h3><span>{positions.length} holdings</span></div><div className="table-head positions-head"><span>INSTRUMENT</span><span>QUANTITY / AVG</span><span>LAST / VALUE</span><span>P&amp;L</span></div>{positions.length?positions.map(p=><div className="table-row position-row" key={p.symbol}><span className="symbol-cell">{p.symbol.replace('.NS','')}<small>DEMO HOLDING</small></span><span>{p.quantity} <small>avg ₹{Number(p.avg_price).toFixed(2)}</small></span><span>₹{Number(p.ltp).toLocaleString('en-IN',{maximumFractionDigits:2})}<small>value ₹{Number(p.current_value).toLocaleString('en-IN',{maximumFractionDigits:0})}</small></span><b className={p.pnl>=0?'positive-text':'negative-text'}>{p.pnl>=0?'+':''}₹{Number(p.pnl).toLocaleString('en-IN',{maximumFractionDigits:0})}<small>{p.pnl_pct>=0?'+':''}{Number(p.pnl_pct).toFixed(2)}%</small></b></div>):<div className="table-state">No open positions in this demo portfolio.</div>}</div></>}
 </div>
}
